import numpy as np
import tkinter as tk
from algos.Solver import *


class AiOPage(tk.Frame):
    def showNE(self,frame,lp,v,rp,lpo,rpo):
        bg_color="#28fa63"
        fg_color="black"
        frame.configure(background=bg_color)
        lp.configure(background=bg_color)
        v.configure(background=bg_color)
        rp.configure(background=bg_color)
        lpo.configure(background=bg_color)
        rpo.configure(background=bg_color)

        lp.configure(foreground=fg_color)
        rp.configure(foreground=fg_color)
        v.configure(foreground=fg_color)

    def solve(self):
        # We need to transofrm our GUI entries to variables  !
        po00=(int(self.payoffEntryL00.get()),int(self.payoffEntryR00.get()))
        po01=(int(self.payoffEntryL01.get()),int(self.payoffEntryR01.get()))
        po10=(int(self.payoffEntryL10.get()),int(self.payoffEntryR10.get()))
        po11=(int(self.payoffEntryL11.get()),int(self.payoffEntryR11.get()))
        payoff=[[po00,po01],[po10,po11]]
        M=np.array(payoff)
        s = Solver(payoff=M)
        result=s.solve(1, 0)

        po00=(self.payoffFrame00,self.payoffLP00,self.payoffV00,
              self.payoffRP00,self.payoffEntryL00,self.payoffEntryR00)
        po01=(self.payoffFrame01,self.payoffLP01,self.payoffV01,
              self.payoffRP01,self.payoffEntryL01,self.payoffEntryR01)
        po10=(self.payoffFrame10,self.payoffLP10,self.payoffV10,
              self.payoffRP10,self.payoffEntryL10,self.payoffEntryR10)
        po11=(self.payoffFrame11,self.payoffLP11,self.payoffV11,
              self.payoffRP11,self.payoffEntryL11,self.payoffEntryR11)

        show_ne=[po00,po01,po10,po11]
        print(result)
        res2Show=[]
        for r in result:
            bin_num=str(r[0])+str(r[1])
            idx=int(bin_num,2)
            res2Show.append(idx)

        for i in res2Show:
            self.showNE(show_ne[i][0],show_ne[i][1],show_ne[i][2],
                        show_ne[i][3],show_ne[i][4],show_ne[i][5])

    def __init__(self, parent,controller):
        tk.Frame.__init__(self, parent)
        self.controller = controller
        self.configure(background="#000")


        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'



        self.titleFrame = tk.Frame(self)

        self.titleFrame.place(relx=0.041, rely=0.028, relheight=0.124
                , relwidth=0.928)
        self.titleFrame.configure(relief='flat')
        self.titleFrame.configure(borderwidth="2")
        self.titleFrame.configure(background="#000000")

        self.titleLabel = tk.Label(self.titleFrame)
        self.titleLabel.place(relx=0.168, rely=0.241, height=34, width=600)
        self.titleLabel.configure(background="#000000")
        self.titleLabel.configure(disabledforeground="#a3a3a3")
        self.titleLabel.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.titleLabel.configure(foreground="#fff")
        self.titleLabel.configure(text='''Pure & Mixed Nash Equilibria''')

        self.mainFrame = tk.Frame(self)
        self.mainFrame.place(relx=0.041, rely=0.176, relheight=0.728
                , relwidth=0.922)
        self.mainFrame.configure(relief='flat')
        self.mainFrame.configure(borderwidth="2")
        self.mainFrame.configure(background="#000")

        self.payoffMatrixFrame = tk.Frame(self.mainFrame)
        self.payoffMatrixFrame.place(relx=0.11, rely=0.343, relheight=0.573
                , relwidth=0.605)
        self.payoffMatrixFrame.configure(relief='flat')
        self.payoffMatrixFrame.configure(borderwidth="2")
        self.payoffMatrixFrame.configure(background="#000")

        self.payoffFrame00 = tk.Frame(self.payoffMatrixFrame)
        self.payoffFrame00.place(relx=0.056, rely=0.086, relheight=0.331
                , relwidth=0.417)
        self.payoffFrame00.configure(relief='groove')
        self.payoffFrame00.configure(borderwidth="2")
        self.payoffFrame00.configure(relief="groove")
        self.payoffFrame00.configure(background="#000")
        self.payoffFrame00.configure(highlightbackground="#d9d9d9")
        self.payoffFrame00.configure(highlightcolor="black")

        self.payoffEntryL00 = tk.Entry(self.payoffFrame00)
        self.payoffEntryL00.place(relx=0.161, rely=0.318, height=32
                , relwidth=0.203)
        self.payoffEntryL00.configure(background="#d0d5db")
        self.payoffEntryL00.configure(disabledforeground="#a3a3a3")
        self.payoffEntryL00.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryL00.configure(foreground="#000000")
        self.payoffEntryL00.configure(highlightbackground="#d9d9d9")
        self.payoffEntryL00.configure(highlightcolor="black")
        self.payoffEntryL00.configure(insertbackground="black")
        self.payoffEntryL00.configure(selectbackground="blue")
        self.payoffEntryL00.configure(selectforeground="white")
        self.payoffEntryL00.configure(relief="flat")

        self.payoffEntryR00 = tk.Entry(self.payoffFrame00)
        self.payoffEntryR00.place(relx=0.594, rely=0.318, height=32
                , relwidth=0.203)
        self.payoffEntryR00.configure(background="#d0d5db")
        self.payoffEntryR00.configure(disabledforeground="#a3a3a3")
        self.payoffEntryR00.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryR00.configure(foreground="#000000")
        self.payoffEntryR00.configure(highlightbackground="#d9d9d9")
        self.payoffEntryR00.configure(highlightcolor="black")
        self.payoffEntryR00.configure(insertbackground="black")
        self.payoffEntryR00.configure(selectbackground="blue")
        self.payoffEntryR00.configure(selectforeground="white")
        self.payoffEntryR00.configure(relief="flat")

        self.payoffLP00 = tk.Label(self.payoffFrame00)
        self.payoffLP00.place(relx=0.051, rely=0.216, height=40, width=16)
        self.payoffLP00.configure(activebackground="#f9f9f9")
        self.payoffLP00.configure(activeforeground="black")
        self.payoffLP00.configure(background="#000")
        self.payoffLP00.configure(disabledforeground="#a3a3a3")
        self.payoffLP00.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffLP00.configure(foreground="#fff")
        self.payoffLP00.configure(highlightbackground="#d9d9d9")
        self.payoffLP00.configure(highlightcolor="black")
        self.payoffLP00.configure(text='''(''')

        self.payoffRP00 = tk.Label(self.payoffFrame00)
        self.payoffRP00.place(relx=0.871, rely=0.216, height=40, width=16)
        self.payoffRP00.configure(activebackground="#f9f9f9")
        self.payoffRP00.configure(activeforeground="black")
        self.payoffRP00.configure(background="#000")
        self.payoffRP00.configure(disabledforeground="#a3a3a3")
        self.payoffRP00.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffRP00.configure(foreground="#fff")
        self.payoffRP00.configure(highlightbackground="#d9d9d9")
        self.payoffRP00.configure(highlightcolor="black")
        self.payoffRP00.configure(text=''')''')

        self.payoffV00 = tk.Label(self.payoffFrame00)
        self.payoffV00.place(relx=0.433, rely=0.102, height=52, width=28)
        self.payoffV00.configure(activebackground="#f9f9f9")
        self.payoffV00.configure(activeforeground="black")
        self.payoffV00.configure(background="#000")
        self.payoffV00.configure(disabledforeground="#a3a3a3")
        self.payoffV00.configure(font="-family {Segoe UI Emoji} -size 28 -weight bold")
        self.payoffV00.configure(foreground="#fff")
        self.payoffV00.configure(highlightbackground="#d9d9d9")
        self.payoffV00.configure(highlightcolor="black")
        self.payoffV00.configure(text=''',''')

        self.payoffFrame01 = tk.Frame(self.payoffMatrixFrame)
        self.payoffFrame01.place(relx=0.478, rely=0.086, relheight=0.331
                , relwidth=0.417)
        self.payoffFrame01.configure(relief='groove')
        self.payoffFrame01.configure(borderwidth="2")
        self.payoffFrame01.configure(relief="groove")
        self.payoffFrame01.configure(background="#000")
        self.payoffFrame01.configure(highlightbackground="#d9d9d9")
        self.payoffFrame01.configure(highlightcolor="black")

        self.payoffEntryL01 = tk.Entry(self.payoffFrame01)
        self.payoffEntryL01.place(relx=0.161, rely=0.318, height=32
                , relwidth=0.203)
        self.payoffEntryL01.configure(background="#d0d5db")
        self.payoffEntryL01.configure(disabledforeground="#a3a3a3")
        self.payoffEntryL01.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryL01.configure(foreground="#000000")
        self.payoffEntryL01.configure(highlightbackground="#d9d9d9")
        self.payoffEntryL01.configure(highlightcolor="black")
        self.payoffEntryL01.configure(insertbackground="black")
        self.payoffEntryL01.configure(selectbackground="blue")
        self.payoffEntryL01.configure(selectforeground="white")
        self.payoffEntryL01.configure(relief="flat")

        self.payoffEntryR01 = tk.Entry(self.payoffFrame01)
        self.payoffEntryR01.place(relx=0.594, rely=0.318, height=32
                , relwidth=0.203)
        self.payoffEntryR01.configure(background="#d0d5db")
        self.payoffEntryR01.configure(disabledforeground="#a3a3a3")
        self.payoffEntryR01.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryR01.configure(foreground="#000000")
        self.payoffEntryR01.configure(highlightbackground="#d9d9d9")
        self.payoffEntryR01.configure(highlightcolor="black")
        self.payoffEntryR01.configure(insertbackground="black")
        self.payoffEntryR01.configure(selectbackground="blue")
        self.payoffEntryR01.configure(selectforeground="white")
        self.payoffEntryR01.configure(relief="flat")

        self.payoffLP01 = tk.Label(self.payoffFrame01)
        self.payoffLP01.place(relx=0.051, rely=0.216, height=40, width=16)
        self.payoffLP01.configure(activebackground="#f9f9f9")
        self.payoffLP01.configure(activeforeground="black")
        self.payoffLP01.configure(background="#000")
        self.payoffLP01.configure(disabledforeground="#a3a3a3")
        self.payoffLP01.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffLP01.configure(foreground="#fff")
        self.payoffLP01.configure(highlightbackground="#d9d9d9")
        self.payoffLP01.configure(highlightcolor="black")
        self.payoffLP01.configure(text='''(''')

        self.payoffRP01 = tk.Label(self.payoffFrame01)
        self.payoffRP01.place(relx=0.871, rely=0.216, height=40, width=16)
        self.payoffRP01.configure(activebackground="#f9f9f9")
        self.payoffRP01.configure(activeforeground="black")
        self.payoffRP01.configure(background="#000")
        self.payoffRP01.configure(disabledforeground="#a3a3a3")
        self.payoffRP01.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffRP01.configure(foreground="#fff")
        self.payoffRP01.configure(highlightbackground="#d9d9d9")
        self.payoffRP01.configure(highlightcolor="black")
        self.payoffRP01.configure(text=''')''')

        self.payoffV01 = tk.Label(self.payoffFrame01)
        self.payoffV01.place(relx=0.433, rely=0.102, height=52, width=28)
        self.payoffV01.configure(activebackground="#f9f9f9")
        self.payoffV01.configure(activeforeground="black")
        self.payoffV01.configure(background="#000")
        self.payoffV01.configure(disabledforeground="#a3a3a3")
        self.payoffV01.configure(font="-family {Segoe UI Emoji} -size 28 -weight bold")
        self.payoffV01.configure(foreground="#fff")
        self.payoffV01.configure(highlightbackground="#d9d9d9")
        self.payoffV01.configure(highlightcolor="black")
        self.payoffV01.configure(text=''',''')

        self.payoffFrame10 = tk.Frame(self.payoffMatrixFrame)
        self.payoffFrame10.place(relx=0.056, rely=0.436, relheight=0.327
                , relwidth=0.417)
        self.payoffFrame10.configure(relief='groove')
        self.payoffFrame10.configure(borderwidth="2")
        self.payoffFrame10.configure(relief="groove")
        self.payoffFrame10.configure(background="#000")
        self.payoffFrame10.configure(highlightbackground="#d9d9d9")
        self.payoffFrame10.configure(highlightcolor="black")

        self.payoffEntryL10 = tk.Entry(self.payoffFrame10)
        self.payoffEntryL10.place(relx=0.161, rely=0.31, height=32
                , relwidth=0.203)
        self.payoffEntryL10.configure(background="#d0d5db")
        self.payoffEntryL10.configure(disabledforeground="#a3a3a3")
        self.payoffEntryL10.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryL10.configure(foreground="#000000")
        self.payoffEntryL10.configure(highlightbackground="#d9d9d9")
        self.payoffEntryL10.configure(highlightcolor="black")
        self.payoffEntryL10.configure(insertbackground="black")
        self.payoffEntryL10.configure(selectbackground="blue")
        self.payoffEntryL10.configure(selectforeground="white")
        self.payoffEntryL10.configure(relief="flat")

        self.payoffEntryR10 = tk.Entry(self.payoffFrame10)
        self.payoffEntryR10.place(relx=0.594, rely=0.31, height=32
                , relwidth=0.203)
        self.payoffEntryR10.configure(background="#d0d5db")
        self.payoffEntryR10.configure(relief='flat')
        self.payoffEntryR10.configure(disabledforeground="#a3a3a3")
        self.payoffEntryR10.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryR10.configure(foreground="#000000")
        self.payoffEntryR10.configure(highlightbackground="#d9d9d9")
        self.payoffEntryR10.configure(highlightcolor="black")
        self.payoffEntryR10.configure(insertbackground="black")
        self.payoffEntryR10.configure(selectbackground="blue")
        self.payoffEntryR10.configure(selectforeground="white")
        self.payoffEntryR10.configure(relief="flat")

        self.payoffLP10 = tk.Label(self.payoffFrame10)
        self.payoffLP10.place(relx=0.051, rely=0.207, height=40, width=16)
        self.payoffLP10.configure(activebackground="#f9f9f9")
        self.payoffLP10.configure(activeforeground="black")
        self.payoffLP10.configure(background="#000")
        self.payoffLP10.configure(disabledforeground="#a3a3a3")
        self.payoffLP10.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffLP10.configure(foreground="#fff")
        self.payoffLP10.configure(highlightbackground="#d9d9d9")
        self.payoffLP10.configure(highlightcolor="black")
        self.payoffLP10.configure(text='''(''')

        self.payoffRP10 = tk.Label(self.payoffFrame10)
        self.payoffRP10.place(relx=0.871, rely=0.207, height=40, width=16)
        self.payoffRP10.configure(activebackground="#f9f9f9")
        self.payoffRP10.configure(activeforeground="black")
        self.payoffRP10.configure(background="#000")
        self.payoffRP10.configure(disabledforeground="#a3a3a3")
        self.payoffRP10.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffRP10.configure(foreground="#fff")
        self.payoffRP10.configure(highlightbackground="#d9d9d9")
        self.payoffRP10.configure(highlightcolor="black")
        self.payoffRP10.configure(text=''')''')

        self.payoffV10 = tk.Label(self.payoffFrame10)
        self.payoffV10.place(relx=0.433, rely=0.103, height=51, width=28)
        self.payoffV10.configure(activebackground="#f9f9f9")
        self.payoffV10.configure(activeforeground="black")
        self.payoffV10.configure(background="#000")
        self.payoffV10.configure(disabledforeground="#a3a3a3")
        self.payoffV10.configure(font="-family {Segoe UI Emoji} -size 28 -weight bold")
        self.payoffV10.configure(foreground="#fff")
        self.payoffV10.configure(highlightbackground="#d9d9d9")
        self.payoffV10.configure(highlightcolor="black")
        self.payoffV10.configure(text=''',''')


        self.payoffFrame11 = tk.Frame(self.payoffMatrixFrame)
        self.payoffFrame11.place(relx=0.478, rely=0.436, relheight=0.327
                , relwidth=0.417)
        self.payoffFrame11.configure(relief='groove')
        self.payoffFrame11.configure(borderwidth="2")
        self.payoffFrame11.configure(relief="groove")
        self.payoffFrame11.configure(background="#000")
        self.payoffFrame11.configure(highlightbackground="#d9d9d9")
        self.payoffFrame11.configure(highlightcolor="black")

        self.payoffEntryL11 = tk.Entry(self.payoffFrame11)
        self.payoffEntryL11.place(relx=0.161, rely=0.31, height=32
                , relwidth=0.203)
        self.payoffEntryL11.configure(background="#d0d5db")
        self.payoffEntryL11.configure(disabledforeground="#a3a3a3")
        self.payoffEntryL11.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryL11.configure(foreground="#000000")
        self.payoffEntryL11.configure(highlightbackground="#d9d9d9")
        self.payoffEntryL11.configure(highlightcolor="black")
        self.payoffEntryL11.configure(insertbackground="black")
        self.payoffEntryL11.configure(selectbackground="blue")
        self.payoffEntryL11.configure(selectforeground="white")
        self.payoffEntryL11.configure(relief="flat")

        self.payoffEntryR11 = tk.Entry(self.payoffFrame11)
        self.payoffEntryR11.place(relx=0.594, rely=0.31, height=32
                , relwidth=0.203)
        self.payoffEntryR11.configure(background="#d0d5db")
        self.payoffEntryR11.configure(disabledforeground="#a3a3a3")
        self.payoffEntryR11.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.payoffEntryR11.configure(foreground="#000000")
        self.payoffEntryR11.configure(highlightbackground="#d9d9d9")
        self.payoffEntryR11.configure(highlightcolor="black")
        self.payoffEntryR11.configure(insertbackground="black")
        self.payoffEntryR11.configure(selectbackground="blue")
        self.payoffEntryR11.configure(selectforeground="white")
        self.payoffEntryR11.configure(relief="flat")

        self.payoffLP11 = tk.Label(self.payoffFrame11)
        self.payoffLP11.place(relx=0.051, rely=0.207, height=40, width=16)
        self.payoffLP11.configure(activebackground="#f9f9f9")
        self.payoffLP11.configure(activeforeground="black")
        self.payoffLP11.configure(background="#000")
        self.payoffLP11.configure(disabledforeground="#a3a3a3")
        self.payoffLP11.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffLP11.configure(foreground="#fff")
        self.payoffLP11.configure(highlightbackground="#d9d9d9")
        self.payoffLP11.configure(highlightcolor="black")
        self.payoffLP11.configure(text='''(''')

        self.payoffRP11 = tk.Label(self.payoffFrame11)
        self.payoffRP11.place(relx=0.871, rely=0.207, height=40, width=16)
        self.payoffRP11.configure(activebackground="#f9f9f9")
        self.payoffRP11.configure(activeforeground="black")
        self.payoffRP11.configure(background="#000")
        self.payoffRP11.configure(disabledforeground="#a3a3a3")
        self.payoffRP11.configure(font="-family {Segoe UI Emoji} -size 22 -weight bold")
        self.payoffRP11.configure(foreground="#fff")
        self.payoffRP11.configure(highlightbackground="#d9d9d9")
        self.payoffRP11.configure(highlightcolor="black")
        self.payoffRP11.configure(text=''')''')

        self.payoffV11 = tk.Label(self.payoffFrame11)
        self.payoffV11.place(relx=0.433, rely=0.103, height=51, width=28)
        self.payoffV11.configure(activebackground="#f9f9f9")
        self.payoffV11.configure(activeforeground="black")
        self.payoffV11.configure(background="#000")
        self.payoffV11.configure(disabledforeground="#a3a3a3")
        self.payoffV11.configure(font="-family {Segoe UI Emoji} -size 28 -weight bold")
        self.payoffV11.configure(foreground="#fff")
        self.payoffV11.configure(highlightbackground="#d9d9d9")
        self.payoffV11.configure(highlightcolor="black")
        self.payoffV11.configure(text=''',''')


        self.Label1_2 = tk.Label(self.mainFrame)
        self.Label1_2.place(relx=0.01, rely=0.422, height=43, width=78)
        self.Label1_2.configure(activebackground="#f9f9f9")
        self.Label1_2.configure(activeforeground="black")
        self.Label1_2.configure(background="#000")
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.Label1_2.configure(foreground="#1efff3")
        self.Label1_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2.configure(highlightcolor="black")
        self.Label1_2.configure(text='''A''')

        self.Label1_2_2 = tk.Label(self.mainFrame)
        self.Label1_2_2.place(relx=0.01, rely=0.625, height=43, width=78)
        self.Label1_2_2.configure(activebackground="#f9f9f9")
        self.Label1_2_2.configure(activeforeground="black")
        self.Label1_2_2.configure(background="#000")
        self.Label1_2_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2_2.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.Label1_2_2.configure(foreground="#1efff3")
        self.Label1_2_2.configure(highlightbackground="#d9d9d9")
        self.Label1_2_2.configure(highlightcolor="black")
        self.Label1_2_2.configure(text='''B''')

        self.Label1_2_3 = tk.Label(self.mainFrame)
        self.Label1_2_3.place(relx=0.22, rely=0.222, height=43, width=78)
        self.Label1_2_3.configure(activebackground="#f9f9f9")
        self.Label1_2_3.configure(activeforeground="black")
        self.Label1_2_3.configure(background="#000")
        self.Label1_2_3.configure(disabledforeground="#a3a3a3")
        self.Label1_2_3.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.Label1_2_3.configure(foreground="#ff3136")
        self.Label1_2_3.configure(highlightbackground="#d9d9d9")
        self.Label1_2_3.configure(highlightcolor="black")
        self.Label1_2_3.configure(text='''C''')

        self.Label1_2_4 = tk.Label(self.mainFrame)
        self.Label1_2_4.place(relx=0.473, rely=0.222, height=43, width=78)
        self.Label1_2_4.configure(activebackground="#f9f9f9")
        self.Label1_2_4.configure(activeforeground="black")
        self.Label1_2_4.configure(background="#000")
        self.Label1_2_4.configure(disabledforeground="#a3a3a3")
        self.Label1_2_4.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.Label1_2_4.configure(foreground="#ff3136")
        self.Label1_2_4.configure(highlightbackground="#d9d9d9")
        self.Label1_2_4.configure(highlightcolor="black")
        self.Label1_2_4.configure(text='''D''')

        self.Label1 = tk.Label(self.mainFrame)
        self.Label1.place(relx=0.297, rely=0.06, height=52, width=153)
        self.Label1.configure(background="#000")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Emoji} -size 20 -weight bold")
        self.Label1.configure(foreground="#ff3136")
        self.Label1.configure(text='''Player II''')

        self.Button1 = tk.Button(self.mainFrame)
        self.Button1.place(relx=0.720, rely=0.520, height=63, width=136)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#000")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font="-family {MV Boli} -size 24")
        self.Button1.configure(foreground="#61ff33")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(relief="groove")
        self.Button1.configure(text='''Solve''')

        self.btnRetour = tk.Button(self.mainFrame)
        self.btnRetour.place(relx=0.031, rely=0.916, height=40, width=145)
        self.btnRetour.configure(activebackground="#ff3d5e")
        self.btnRetour.configure(activeforeground="#000000")
        self.btnRetour.configure(background="#000")
        self.btnRetour.configure(disabledforeground="#a3a3a3")
        self.btnRetour.configure(font="-family {MV Boli} -size 20")
        self.btnRetour.configure(foreground="#ff3d5e")
        self.btnRetour.configure(highlightbackground="#d9d9d9")
        self.btnRetour.configure(highlightcolor="black")
        self.btnRetour.configure(pady="0")
        self.btnRetour.configure(relief="groove")
        self.btnRetour.configure(text='''Go Back''')
        self.Button1.configure(command= lambda : self.solve())
        self.btnRetour.configure(command=lambda: controller.show_frame("WelcomePage"))